Support for AL_SESSION_COOKIE_SAMESITE environment variable
CybercentreCanada/assemblyline-helm-chart pull request #94
Opened 2024-01-19 05:34 UTC by microblag

See https://github.com/CybercentreCanada/assemblyline-ui/pull/819 for details on what this environment variable does.

2024-02-14 13:53 UTC, cccs-sgaron requested changes
We should have a default value for enableSessionCookieSamesite and sessionCookieSamesite in the values.yml file with enableSessionCookieSamesite set to false.

2024-02-19 22:44 UTC, microblag commented
Thanks @cccs-sgaron
I've added defaults to values.yaml

2024-02-21 13:02 UTC, cccs-sgaron approved these changes

2024-02-21 13:29 UTC, cccs-rs approved these changes

2024-02-27 17:04 UTC, cccs-rs commented
Closing in favour of: https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/109

2024-02-27 17:04 UTC, closed without merging